import { type Metadata } from "next";
import {
  ClerkProvider
} from "@clerk/nextjs";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { Spotlight } from "./portfolio/components/Spotlight";
import ClientLayout from "@/Providers";

const montserrat = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${montserrat.className} main-bg-noise antialiased`}
        >
          <ClientLayout>{children}</ClientLayout>
        </body>
      </html>
  );
}
