import { type Metadata } from "next";
import {
  ClerkProvider
} from "@clerk/nextjs";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { Spotlight } from "./portfolio/components/Spotlight";

const montserrat = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${montserrat.className} main-bg-noise antialiased`}
        >
          {/* <div className="absolute inset-0">
          <Spotlight
            className="-top-40 left-0 md:-top-80 md:left-5"
            fill="white"
          />
        </div> */}
      <Toaster />

          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
